name: WakaTime

on:
  push:
    branches:
      - main
  workflow_dispatch:
  schedule:
    - cron: "42 0 * * *"

jobs:
  update-readme:
    name: Update Watatime stats on README
    runs-on: ubuntu-latest
    steps:
      - uses: athul/waka-readme@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
